name: Generate Android Keystore (one-off)
on: workflow_dispatch

jobs:
  gen-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore upload-keystore.jks -storepass changeit \
            -alias upload -keypass changeit -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=DIV, OU=DIV, O=DIV, L=Prague, S=CZ, C=CZ"
          base64 upload-keystore.jks > keystore.base64
          echo "----- BELOW IS YOUR BASE64 KEYSTORE -----"
          cat keystore.base64
